In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

my_list = [1, 2, 3, 4, 5]

print(my_list)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
zero = np.zeros((3, 3))

print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
one = np.ones((3, 3))

print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
random = np.random.random((4, 4))

print(random)

[[0.63409686 0.68280104 0.6208368  0.69605321]
 [0.45967201 0.11102127 0.89337466 0.21785278]
 [0.21235326 0.02733538 0.52804936 0.63307012]
 [0.74026604 0.01115965 0.90821468 0.96354653]]


In [11]:
onedarray = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

onedarray = onedarray.reshape(2,5)

print(onedarray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
onedarray = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

print(onedarray)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
twodarray = np.array([[1, 2, 3,4], [4, 5, 6,7]])

print(twodarray)

[[1 2 3 4]
 [4 5 6 7]]


In [3]:
indentity = np.identity(3)

print(indentity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1]:
import numpy as np

onedarray = np.array([x for x in range(11)])
print(onedarray)



[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
arr1 = np.random.random((3, 3))
arr2 = np.ones((3, 3))

print(arr1 + arr2)
print(np.add(arr1, arr2))

[[1.4836606  1.28237563 1.33558005]
 [1.09980299 1.38515457 1.76922756]
 [1.75873256 1.03740371 1.27825835]]
[[1.4836606  1.28237563 1.33558005]
 [1.09980299 1.38515457 1.76922756]
 [1.75873256 1.03740371 1.27825835]]


In [9]:
arr =np.array([0,np.pi/2,np.pi])

print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))
print(np.exp(arr))
print(np.sqrt(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[ 1.          4.81047738 23.14069263]
[0.         1.25331414 1.77245385]


In [13]:
import numpy as np

array = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [1, 2, 3, 4]])

print(array)
print(np.sum(array))


[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]]
42


In [19]:
import numpy as np

# Create a 3x3x6 array with random values
arr3 = np.random.random((3, 3, 3))

# Print the array
print(arr3)

# Print the shape of the array
print(arr3.shape)



[[[0.9870166  0.80303345 0.78799317]
  [0.70659807 0.63048501 0.54803815]
  [0.97565821 0.92713474 0.31384373]]

 [[0.92901138 0.16706074 0.00607087]
  [0.29718142 0.92605484 0.62955041]
  [0.59225852 0.33624084 0.46939446]]

 [[0.45539919 0.91322279 0.8906069 ]
  [0.80084169 0.78819496 0.6294017 ]
  [0.84473326 0.9988449  0.19345634]]]
(3, 3, 3)


In [22]:

import numpy as np

arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [1, 2, 3, 4]])

print(arr.shape)

print(arr)

print(arr[0][0])

(3, 4)
[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]]
1


In [29]:
import numpy as np
arr3 = np.random.random((2,2,3))

print(arr3)

print(arr3[0][1][1])

[[[0.883144   0.4477925  0.19765836]
  [0.34253395 0.2279964  0.95813018]]

 [[0.42203045 0.92127711 0.25440851]
  [0.63622718 0.36246205 0.71327308]]]
0.2279964021647689


In [34]:
arr_new = arr3[0:1,0:1,0:2]

print(arr_new)

[[[0.883144  0.4477925]]]


In [39]:
arr4 = np.random.random((4,4,4,4))

print(arr4)

new_arr = arr4[0:1,0:1,0:2,0:1]

print(new_arr)

[[[[6.05135030e-01 1.52143016e-01 9.41483689e-01 5.77948796e-01]
   [4.38806873e-01 4.28949184e-01 4.89944406e-01 4.41371744e-01]
   [8.00740215e-01 7.84053943e-01 3.77636236e-02 5.72569895e-01]
   [9.33719454e-01 9.52158762e-01 8.62156602e-01 4.43897074e-01]]

  [[8.01742320e-01 9.57448138e-01 8.51875712e-01 8.51324124e-01]
   [4.64615240e-01 5.99540186e-01 5.93111732e-01 8.39903068e-01]
   [6.83631808e-01 6.73838107e-01 2.22056948e-01 9.18517634e-01]
   [9.77092491e-01 3.61181307e-01 1.82302600e-01 7.83145857e-01]]

  [[8.94866838e-01 8.29512150e-01 7.88483584e-01 6.46012155e-01]
   [8.88639022e-01 4.45458898e-01 7.80934818e-01 1.47243027e-01]
   [1.92614396e-01 4.26521591e-01 5.55739995e-01 7.69841537e-01]
   [2.76419488e-01 3.88602685e-01 8.06879294e-01 8.52896405e-01]]

  [[7.66233324e-01 5.67287081e-01 1.53984240e-01 7.71824752e-01]
   [9.66007538e-01 5.31915947e-01 6.50147939e-01 9.54071025e-01]
   [9.47311808e-01 9.47865163e-01 1.57130974e-01 4.68469184e-01]
   [2.51301870e-01 

In [40]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

flattend_arr = arr_2d.flatten()

print(flattend_arr)

[1 2 3 4 5 6 7 8 9]


In [42]:
new_ARRAY = arr4.flatten()

print(new_ARRAY)

[6.05135030e-01 1.52143016e-01 9.41483689e-01 5.77948796e-01
 4.38806873e-01 4.28949184e-01 4.89944406e-01 4.41371744e-01
 8.00740215e-01 7.84053943e-01 3.77636236e-02 5.72569895e-01
 9.33719454e-01 9.52158762e-01 8.62156602e-01 4.43897074e-01
 8.01742320e-01 9.57448138e-01 8.51875712e-01 8.51324124e-01
 4.64615240e-01 5.99540186e-01 5.93111732e-01 8.39903068e-01
 6.83631808e-01 6.73838107e-01 2.22056948e-01 9.18517634e-01
 9.77092491e-01 3.61181307e-01 1.82302600e-01 7.83145857e-01
 8.94866838e-01 8.29512150e-01 7.88483584e-01 6.46012155e-01
 8.88639022e-01 4.45458898e-01 7.80934818e-01 1.47243027e-01
 1.92614396e-01 4.26521591e-01 5.55739995e-01 7.69841537e-01
 2.76419488e-01 3.88602685e-01 8.06879294e-01 8.52896405e-01
 7.66233324e-01 5.67287081e-01 1.53984240e-01 7.71824752e-01
 9.66007538e-01 5.31915947e-01 6.50147939e-01 9.54071025e-01
 9.47311808e-01 9.47865163e-01 1.57130974e-01 4.68469184e-01
 2.51301870e-01 1.27416516e-01 6.47707166e-01 4.75906176e-01
 5.01491935e-01 2.667362

In [46]:
new_ARRAY4 = arr4.reshape(2, 128)
print("Reshaped array:")
print(new_ARRAY4)
print("New shape:", new_ARRAY4.shape)

Reshaped array:
[[6.05135030e-01 1.52143016e-01 9.41483689e-01 5.77948796e-01
  4.38806873e-01 4.28949184e-01 4.89944406e-01 4.41371744e-01
  8.00740215e-01 7.84053943e-01 3.77636236e-02 5.72569895e-01
  9.33719454e-01 9.52158762e-01 8.62156602e-01 4.43897074e-01
  8.01742320e-01 9.57448138e-01 8.51875712e-01 8.51324124e-01
  4.64615240e-01 5.99540186e-01 5.93111732e-01 8.39903068e-01
  6.83631808e-01 6.73838107e-01 2.22056948e-01 9.18517634e-01
  9.77092491e-01 3.61181307e-01 1.82302600e-01 7.83145857e-01
  8.94866838e-01 8.29512150e-01 7.88483584e-01 6.46012155e-01
  8.88639022e-01 4.45458898e-01 7.80934818e-01 1.47243027e-01
  1.92614396e-01 4.26521591e-01 5.55739995e-01 7.69841537e-01
  2.76419488e-01 3.88602685e-01 8.06879294e-01 8.52896405e-01
  7.66233324e-01 5.67287081e-01 1.53984240e-01 7.71824752e-01
  9.66007538e-01 5.31915947e-01 6.50147939e-01 9.54071025e-01
  9.47311808e-01 9.47865163e-01 1.57130974e-01 4.68469184e-01
  2.51301870e-01 1.27416516e-01 6.47707166e-01 4.75906

In [2]:
arr10 = np.array([1, 2, 3, 4])
arr11 = np.array([[5], [6], [7], [8]])

print(arr10 + arr11)

mul = arr10 * arr11

mult = np.dot(arr10, arr11)

print(mult,'the dot product')
print(mul)

NameError: name 'np' is not defined

In [ ]:
list10 = [1, 2, 3, 4]

list11 = [[5], [6], [7], [8]]

print(list10 + list11)


: 

In [ ]:
import matplotlib.pyplot as plt


# x = [1, 2, 3, 4]

# y = [1, 4, 9, 16]

x =np.random.random((10)).tolist()
y =np.random.random((10)).tolist()
plt.plot(x, y)
plt.title("Line Graph")
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.show()

: 